[package]
name = "hyper-python"
version = "0.1.0"
edition = "2021"

[lib]
name = "_hyper_native"
crate-type = ["cdylib"]

[dependencies]
hyper-transpiler = { path = "../transpiler" }
pyo3 = { version = "0.23", features = ["extension-module", "abi3-py39"] }